### ISSUE TITLE
Create missing components

### ISSUE THREAD

**Issue by sandroschutt** [sandroschutt/r3e-app#18]
- [x] notifications
- [ ] settings
- [ ] user evaluation

[figma > Parts](https://www.figma.com/file/8JKqO1AESPhHBjGCL7hrXd/Descarte-Sustent%C3%A1vel?type=design&node-id=0-1&mode=design)

**Comment by gabrielschut** [comment]
https://drive.google.com/file/d/117A_zNIZxVMuDi8UuKl-QeRhInnVHHR-/view?usp=drive_link
https://drive.google.com/file/d/1m4FXJdvG2w1RaBFr55U_MGhUOsZzRtO1/view?usp=drive_link

**Comment by gabrielschut** [comment]
@sandroschutt PR com o notifications modal criado.
Comecei uma nova branch da main atual para evitar conflitos desnecessários.

https://github.com/sandroschutt/r3e-app/pull/53
